version: '3'
services:
  model:
    # Choose container name
    container_name: model-service

    # If the image is already created
    # image: modelimage:latest

    # If the image is not created
    build: "." # path to Dockerfile

    # Route the desire ports <LOCAL>:<DOCKER>
    ports:
     - "7000:7000"

    # Path to the project folder <LOCAL>:<DOCKER>
    volumes:
     - .:/app 

    # If the image uses GPU
    # runtime: nvidia